import {
  slugifyValue,
  type InterviewDifficulty,
  type InterviewFirmType,
  type InterviewQuestionType,
  type InterviewRole,
} from '@/lib/interview-tool/taxonomy';

export interface InterviewSeedQuestion {
  seedKey: string;
  question: string;
  answer: string;
  notes: string | null;
  role: InterviewRole;
  subcategory: string | null;
  questionType: InterviewQuestionType;
  difficulty: InterviewDifficulty;
  company: string | null;
  firmType: InterviewFirmType | null;
  topicTags: string[];
  sourceType: string;
  sourceTitle: string;
  sourceUrl: string | null;
  attachmentUrl: string | null;
  submitterName: string;
  submittedBy: string | null;
  approved: boolean;
}

interface TrackMeta {
  role: InterviewRole;
  subcategory: string | null;
  label: string;
  product: string;
  deliverable: string;
  counterpart: string;
  workflow: string;
  focus: string;
  coreSignal: string;
  drivers: [string, string, string];
  risks: [string, string, string];
  skills: [string, string, string];
  metrics: [string, string, string];
  firms: string[];
  firmType: InterviewFirmType;
  tags: string[];
}

interface QuestionBlueprint {
  key: string;
  questionType: InterviewQuestionType;
  difficulty: InterviewDifficulty;
  tags: string[];
  buildQuestion: (meta: TrackMeta, firm: string) => string;
  buildAnswer: (meta: TrackMeta, firm: string) => string;
}

const SOURCE_TITLE = 'SGC Interview Bank v1';

const TRACKS: TrackMeta[] = [
  {
    role: 'sales_trading',
    subcategory: 'ai_roles',
    label: 'AI Roles in Markets',
    product: 'AI-enabled market intelligence and execution tooling',
    deliverable: 'turn noisy data into repeatable decisions that help the desk price risk faster',
    counterpart: 'traders, salespeople, and engineers',
    workflow: 'define the decision, source clean data, test the model, and ship it with clear guardrails',
    focus: 'using machine learning only where it adds measurable edge over a simpler baseline',
    coreSignal: 'whether the model improves decision quality after costs, latency, and false positives',
    drivers: ['data quality', 'latency constraints', 'model drift'],
    risks: ['overfitting', 'poor production monitoring', 'using a black-box signal without a kill switch'],
    skills: ['feature engineering', 'statistical validation', 'clear model monitoring'],
    metrics: ['precision versus baseline', 'latency to decision', 'post-deployment hit rate'],
    firms: ['Citadel Securities', 'Jane Street', 'Hudson River Trading', 'Optiver'],
    firmType: 'market_maker',
    tags: ['ai', 'markets', 'machine-learning'],
  },
  {
    role: 'sales_trading',
    subcategory: 'quant_trading',
    label: 'Quant Trading',
    product: 'systematic signals and automated execution',
    deliverable: 'translate a statistical edge into pnl after transaction costs and risk limits',
    counterpart: 'traders, quants, and risk managers',
    workflow: 'form a hypothesis, test it robustly, size it prudently, and monitor live performance',
    focus: 'maintaining discipline when the live strategy deviates from the backtest',
    coreSignal: 'whether the strategy keeps a stable edge net of fees, slippage, and crowding',
    drivers: ['microstructure changes', 'cost of execution', 'signal decay'],
    risks: ['regime breaks', 'hidden correlation', 'capacity constraints'],
    skills: ['probability', 'backtesting hygiene', 'position sizing'],
    metrics: ['sharpe after costs', 'hit rate by regime', 'drawdown depth'],
    firms: ['Jump Trading', 'DRW', 'IMC', 'Tower Research'],
    firmType: 'prop_trading',
    tags: ['systematic', 'trading', 'alpha'],
  },
  {
    role: 'sales_trading',
    subcategory: 'quant_research',
    label: 'Quant Research',
    product: 'research frameworks that create durable signals',
    deliverable: 'separate true edge from noise and hand traders a signal they can trust',
    counterpart: 'portfolio managers, traders, and data engineers',
    workflow: 'clean the dataset, define the target, test robustness, and stress the idea across regimes',
    focus: 'being ruthless about data leakage and false discovery',
    coreSignal: 'whether the effect survives out-of-sample, costs, and sensible economic intuition',
    drivers: ['sample selection', 'feature stability', 'economic intuition'],
    risks: ['data leakage', 'multiple testing', 'unstable production features'],
    skills: ['research design', 'cross-validation', 'economic reasoning'],
    metrics: ['out-of-sample information ratio', 'feature stability', 't-stat persistence'],
    firms: ['AQR', 'Two Sigma', 'Point72 Cubist', 'WorldQuant'],
    firmType: 'hedge_fund',
    tags: ['quant', 'research', 'data'],
  },
  {
    role: 'sales_trading',
    subcategory: 'trading_desk',
    label: 'Trading Desk',
    product: 'risk warehousing and principal market-making',
    deliverable: 'price inventory well and make money from spread, flow, and risk transfer',
    counterpart: 'salespeople, clients, and risk',
    workflow: 'read the tape, manage inventory, react to catalysts, and communicate clearly under time pressure',
    focus: 'balancing client service with disciplined inventory management',
    coreSignal: 'whether the desk is getting paid enough spread for the liquidity and inventory risk it takes',
    drivers: ['client flow', 'inventory balance', 'event risk'],
    risks: ['gap risk', 'crowded positioning', 'liquidity drying up at the wrong moment'],
    skills: ['decision-making under pressure', 'inventory management', 'clear risk communication'],
    metrics: ['inventory turnover', 'bid-ask capture', 'pnl volatility'],
    firms: ['Goldman Sachs', 'J.P. Morgan', 'Morgan Stanley', 'Barclays'],
    firmType: 'investment_bank',
    tags: ['desk', 'flow', 'risk'],
  },
  {
    role: 'sales_trading',
    subcategory: 'options_desk',
    label: 'Options Desk',
    product: 'listed and otc optionality',
    deliverable: 'price volatility properly and manage greek exposures dynamically',
    counterpart: 'sales, structurers, and volatility traders',
    workflow: 'understand the client objective, quote vol, hedge the greeks, and re-mark the surface as conditions change',
    focus: 'distinguishing realized versus implied volatility and knowing when skew matters most',
    coreSignal: 'whether the implied vol you sell or buy is attractive relative to realized outcomes and hedging costs',
    drivers: ['realized volatility', 'skew and term structure', 'hedging liquidity'],
    risks: ['short gamma in fast markets', 'vega concentration', 'model risk around correlation or jumps'],
    skills: ['greeks intuition', 'vol surface reading', 'hedging discipline'],
    metrics: ['vega exposure', 'gamma scalp pnl', 'realized versus implied spread'],
    firms: ['Optiver', 'Susquehanna', 'Citigroup', 'Bank of America'],
    firmType: 'market_maker',
    tags: ['options', 'volatility', 'derivatives'],
  },
  {
    role: 'sales_trading',
    subcategory: 'sales_desk',
    label: 'Sales Desk',
    product: 'client coverage and idea distribution',
    deliverable: 'win client trust by bringing timely ideas, access, and execution judgment',
    counterpart: 'institutional clients and internal trading teams',
    workflow: 'understand the client mandate, tailor the idea, coordinate execution, and follow up with value-add',
    focus: 'translating market color into client-specific recommendations',
    coreSignal: 'whether your calls and follow-up make the client more informed and more likely to trade with you again',
    drivers: ['client positioning', 'market catalysts', 'relevance of your idea set'],
    risks: ['generic communication', 'poor follow-through', 'pushing an idea that does not fit the client mandate'],
    skills: ['relationship building', 'market synthesis', 'concise communication'],
    metrics: ['client wallet share', 'idea conversion rate', 'repeat interaction frequency'],
    firms: ['RBC Capital Markets', 'BMO Capital Markets', 'Deutsche Bank', 'UBS'],
    firmType: 'investment_bank',
    tags: ['sales', 'clients', 'coverage'],
  },
  {
    role: 'sales_trading',
    subcategory: 'bonds',
    label: 'Bonds',
    product: 'rates and credit instruments',
    deliverable: 'understand curve, spread, and financing dynamics well enough to quote and manage risk intelligently',
    counterpart: 'issuers, investors, and fixed income traders',
    workflow: 'frame the macro backdrop, understand the curve, compare spread versus fundamentals, and manage duration',
    focus: 'explaining how rates and spreads interact rather than treating them as one trade',
    coreSignal: 'whether the yield properly compensates you for duration, liquidity, and credit risk',
    drivers: ['central bank expectations', 'curve shape', 'credit spread behavior'],
    risks: ['duration shock', 'spread widening', 'funding stress'],
    skills: ['fixed income math', 'curve intuition', 'relative-value framing'],
    metrics: ['duration contribution', 'spread duration', 'carry and roll-down'],
    firms: ['J.P. Morgan', 'BNP Paribas', 'CIBC Capital Markets', 'Wells Fargo'],
    firmType: 'investment_bank',
    tags: ['fixed-income', 'rates', 'credit'],
  },
  {
    role: 'sales_trading',
    subcategory: 'equities',
    label: 'Equities',
    product: 'cash equities and equity-linked flow',
    deliverable: 'match client flow with intelligent execution and tight market color',
    counterpart: 'portfolio managers and equity traders',
    workflow: 'watch liquidity, catalysts, and positioning while adjusting execution to market conditions',
    focus: 'balancing urgency, liquidity, and information leakage',
    coreSignal: 'whether you can improve execution quality without signaling too much to the market',
    drivers: ['liquidity conditions', 'earnings and news flow', 'index and factor positioning'],
    risks: ['market impact', 'short-term news shocks', 'crowded positioning'],
    skills: ['market microstructure', 'execution tactics', 'stock-specific judgment'],
    metrics: ['implementation shortfall', 'fill quality', 'market impact versus benchmark'],
    firms: ['Morgan Stanley', 'Goldman Sachs', 'RBC Capital Markets', 'Jefferies'],
    firmType: 'investment_bank',
    tags: ['equities', 'execution', 'market-structure'],
  },
  {
    role: 'sales_trading',
    subcategory: 'fx',
    label: 'FX',
    product: 'spot, forwards, and options in currencies',
    deliverable: 'connect macro and cross-border flow into tradable currency views',
    counterpart: 'corporates, asset managers, and macro traders',
    workflow: 'track relative growth, inflation, and policy paths while watching positioning and carry',
    focus: 'turning macro views into clean currency expressions with clear catalysts',
    coreSignal: 'whether the rate differential, balance-of-payments story, and positioning all point in the same direction',
    drivers: ['central bank divergence', 'real rate differentials', 'external balance and flow'],
    risks: ['policy surprises', 'correlated risk-off moves', 'crowded carry trades'],
    skills: ['macro synthesis', 'relative-value thinking', 'cross-asset awareness'],
    metrics: ['carry versus spot move', 'policy-path repricing', 'positioning extremes'],
    firms: ['Citi', 'J.P. Morgan', 'Bank of America', 'Standard Chartered'],
    firmType: 'investment_bank',
    tags: ['fx', 'macro', 'currencies'],
  },
  {
    role: 'investment_banking',
    subcategory: 'm_and_a',
    label: 'M&A',
    product: 'strategic acquisitions, divestitures, and merger advisory',
    deliverable: 'help a client evaluate strategic fit, valuation, and execution risk in a transaction',
    counterpart: 'corporate executives, sponsors, and internal deal teams',
    workflow: 'build the market map, understand the rationale, test value creation, and drive the process cleanly',
    focus: 'linking strategy to valuation instead of treating the model as the whole answer',
    coreSignal: 'whether the deal creates value after premium, financing, integration, and execution risk',
    drivers: ['strategic rationale', 'valuation support', 'execution certainty'],
    risks: ['overpaying', 'synergy overestimation', 'integration failure'],
    skills: ['valuation', 'process management', 'executive communication'],
    metrics: ['accretion or dilution', 'premium to unaffected price', 'synergy payback'],
    firms: ['Evercore', 'Goldman Sachs', 'Lazard', 'Morgan Stanley'],
    firmType: 'investment_bank',
    tags: ['m-and-a', 'advisory', 'valuation'],
  },
  {
    role: 'investment_banking',
    subcategory: 'industry_groups',
    label: 'Industry Groups',
    product: 'sector-specific corporate finance coverage',
    deliverable: 'combine sector knowledge with transaction execution so clients trust your advice',
    counterpart: 'management teams, investors, and sector specialists',
    workflow: 'know the sector cold, keep comps fresh, and connect operating drivers to capital markets implications',
    focus: 'earning credibility by understanding what actually matters in the sector',
    coreSignal: 'whether you can explain why the sector is rerating and what that means for financing or strategic options',
    drivers: ['sector growth drivers', 'competitive positioning', 'investor sentiment'],
    risks: ['weak sector knowledge', 'stale comps', 'missing a key catalyst'],
    skills: ['sector analysis', 'comps work', 'synthesizing investor narratives'],
    metrics: ['peer multiple dispersion', 'sector growth outlook', 'capital intensity'],
    firms: ['J.P. Morgan', 'RBC Capital Markets', 'BofA Securities', 'Citi'],
    firmType: 'investment_bank',
    tags: ['industry', 'coverage', 'sector'],
  },
  {
    role: 'investment_banking',
    subcategory: 'capital_markets',
    label: 'Capital Markets',
    product: 'equity and debt issuance',
    deliverable: 'help clients raise capital at the right time, size, and structure',
    counterpart: 'issuers, investors, syndicate, and sales',
    workflow: 'read market windows, position the story, set terms, and manage investor feedback',
    focus: 'matching issuer needs with real investor appetite rather than theoretical valuation alone',
    coreSignal: 'whether the issue clears cleanly with a strong book and healthy aftermarket performance',
    drivers: ['market window quality', 'investor appetite', 'pricing discipline'],
    risks: ['failed bookbuild', 'aftermarket underperformance', 'poor investor targeting'],
    skills: ['bookbuilding intuition', 'market timing', 'transaction structuring'],
    metrics: ['book coverage', 'pricing discount', 'aftermarket trading performance'],
    firms: ['Goldman Sachs', 'Morgan Stanley', 'Barclays', 'RBC Capital Markets'],
    firmType: 'investment_bank',
    tags: ['ecm', 'dcm', 'capital-markets'],
  },
  {
    role: 'investment_banking',
    subcategory: 'restructuring',
    label: 'Restructuring',
    product: 'liability management and distressed advisory',
    deliverable: 'help stakeholders understand value break, liquidity runway, and negotiation leverage',
    counterpart: 'debtors, creditors, and sponsor or creditor committees',
    workflow: 'build the cash flow, understand the capital structure, test recoveries, and map each stakeholder incentive',
    focus: 'being precise about liquidity and value leakage when time is short',
    coreSignal: 'whether the company has enough runway and whether each creditor class is in or out of the money',
    drivers: ['liquidity runway', 'capital structure seniority', 'operating deterioration'],
    risks: ['running out of cash', 'incorrect recovery assumptions', 'misreading stakeholder leverage'],
    skills: ['cash flow modeling', 'capital structure analysis', 'distressed negotiations'],
    metrics: ['minimum cash balance', 'recovery value by tranche', 'interest coverage'],
    firms: ['PJT Partners', 'Houlihan Lokey', 'Lazard', 'Moelis'],
    firmType: 'investment_bank',
    tags: ['restructuring', 'distressed', 'credit'],
  },
  {
    role: 'investment_banking',
    subcategory: 'general_ib',
    label: 'General Investment Banking',
    product: 'broad-based advisory and financing support',
    deliverable: 'be a reliable generalist who can support live deals while learning quickly across products',
    counterpart: 'senior bankers, clients, and product specialists',
    workflow: 'prepare materials accurately, update analysis fast, and keep the team aligned under deadline',
    focus: 'showing judgment early while never becoming sloppy with detail',
    coreSignal: 'whether the team can trust your work without having to rebuild it',
    drivers: ['analytical accuracy', 'responsiveness', 'commercial awareness'],
    risks: ['avoidable errors', 'poor prioritization', 'not understanding the client objective'],
    skills: ['financial modeling', 'attention to detail', 'structured communication'],
    metrics: ['turnaround time', 'error rate', 'quality of first draft materials'],
    firms: ['BMO Capital Markets', 'TD Securities', 'Jefferies', 'CIBC Capital Markets'],
    firmType: 'investment_bank',
    tags: ['ib', 'modeling', 'process'],
  },
  {
    role: 'buyside',
    subcategory: 'hedge_fund',
    label: 'Hedge Fund',
    product: 'high-conviction public market investing',
    deliverable: 'generate differentiated ideas that can survive deep challenge and catalyst timing pressure',
    counterpart: 'portfolio managers, analysts, and traders',
    workflow: 'form the variant view, map catalysts, size the position, and monitor the thesis versus the tape',
    focus: 'finding a reason the market is wrong rather than merely finding a good company',
    coreSignal: 'whether you have a genuine variant perception and a catalyst that can close the gap',
    drivers: ['variant view', 'catalyst path', 'positioning and crowding'],
    risks: ['thesis drift', 'crowded shorts or longs', 'slow catalyst realization'],
    skills: ['idea generation', 'variant perception', 'catalyst analysis'],
    metrics: ['expected upside to downside', 'time to catalyst', 'position contribution to portfolio risk'],
    firms: ['Point72', 'Citadel', 'Pershing Square', 'Millennium'],
    firmType: 'hedge_fund',
    tags: ['hedge-fund', 'ideas', 'catalysts'],
  },
  {
    role: 'buyside',
    subcategory: 'pension',
    label: 'Pension',
    product: 'long-horizon asset allocation and manager selection',
    deliverable: 'compound capital responsibly while matching liabilities and governance constraints',
    counterpart: 'investment committees, external managers, and internal asset allocation teams',
    workflow: 'start from the total fund objective, assess opportunity cost, and size the allocation with risk budgeting in mind',
    focus: 'thinking at the total-portfolio level instead of in isolated silos',
    coreSignal: 'whether the investment improves the plan’s long-run return profile without creating a governance problem',
    drivers: ['liability profile', 'expected real return', 'portfolio diversification'],
    risks: ['illiquidity mismatches', 'manager risk', 'underestimating governance constraints'],
    skills: ['portfolio construction', 'manager diligence', 'long-horizon judgment'],
    metrics: ['funded status sensitivity', 'tracking error to policy portfolio', 'liquidity budget'],
    firms: ['CPP Investments', 'OMERS', 'OTPP', 'PSP Investments'],
    firmType: 'pension',
    tags: ['pension', 'asset-allocation', 'portfolio'],
  },
  {
    role: 'buyside',
    subcategory: 'long_only',
    label: 'Long-Only Investing',
    product: 'fundamental equity investing with benchmark awareness',
    deliverable: 'own businesses that can compound earnings and outperform over a multi-year horizon',
    counterpart: 'portfolio managers, sector analysts, and clients',
    workflow: 'understand business quality, valuation, and position sizing in the context of the rest of the book',
    focus: 'knowing when a great company is not a great stock at the current price',
    coreSignal: 'whether the business can beat embedded expectations and whether valuation leaves room for rerating',
    drivers: ['earnings durability', 'management execution', 'valuation expectations'],
    risks: ['multiple compression', 'thesis complacency', 'benchmark crowding'],
    skills: ['fundamental analysis', 'valuation discipline', 'portfolio context'],
    metrics: ['expected alpha versus benchmark', 'earnings revision trend', 'free cash flow conversion'],
    firms: ['Capital Group', 'Fidelity', 'T. Rowe Price', 'MFS'],
    firmType: 'asset_manager',
    tags: ['long-only', 'equities', 'fundamental'],
  },
  {
    role: 'buyside',
    subcategory: 'asset_management',
    label: 'Asset Management',
    product: 'portfolio solutions across asset classes',
    deliverable: 'deliver repeatable investment outcomes that are aligned with client mandates',
    counterpart: 'clients, consultants, and portfolio teams',
    workflow: 'understand the mandate, evaluate the opportunity, and express the view in a portfolio-aware way',
    focus: 'aligning investment recommendations with the actual risk tolerance and benchmark of the client',
    coreSignal: 'whether the portfolio change improves expected outcomes for the mandate rather than in isolation',
    drivers: ['client objective', 'benchmark design', 'cross-asset opportunity set'],
    risks: ['style drift', 'benchmark mismatch', 'overconcentration'],
    skills: ['portfolio construction', 'client alignment', 'cross-asset thinking'],
    metrics: ['tracking error', 'information ratio', 'client retention'],
    firms: ['BlackRock', 'PIMCO', 'Vanguard', 'Fidelity'],
    firmType: 'asset_manager',
    tags: ['asset-management', 'clients', 'portfolio-construction'],
  },
  {
    role: 'buyside',
    subcategory: 'credit',
    label: 'Buyside Credit',
    product: 'corporate credit and structured opportunities',
    deliverable: 'find mispriced spreads where downside is protected by structure or recovery value',
    counterpart: 'pms, traders, and management teams',
    workflow: 'underwrite cash flows, covenant protection, and recovery scenarios before reaching for spread',
    focus: 'avoiding situations where yield looks attractive only because the downside is poorly understood',
    coreSignal: 'whether the spread compensates for default probability, recovery risk, and liquidity',
    drivers: ['leverage path', 'free cash flow resilience', 'covenant quality'],
    risks: ['refinancing risk', 'weak recoveries', 'liquidity traps'],
    skills: ['credit underwriting', 'capital structure analysis', 'downside scenario work'],
    metrics: ['net leverage', 'interest coverage', 'spread to expected loss'],
    firms: ['Apollo', 'Blue Owl', 'PIMCO', 'Carlyle'],
    firmType: 'asset_manager',
    tags: ['credit', 'underwriting', 'downside'],
  },
  {
    role: 'buyside',
    subcategory: 'macro',
    label: 'Buyside Macro',
    product: 'top-down rates, fx, equity index, and commodity positioning',
    deliverable: 'turn macro regimes into clean expressions with strong asymmetry',
    counterpart: 'macro pm, traders, and risk',
    workflow: 'define the regime, identify the best expression, and map the catalyst path and risk events',
    focus: 'choosing the cleanest expression rather than the most complicated one',
    coreSignal: 'whether your expression captures the macro view with good carry, liquidity, and catalyst timing',
    drivers: ['policy path', 'growth surprises', 'inflation trajectory'],
    risks: ['policy reversals', 'correlated drawdowns', 'wrong expression for the right thesis'],
    skills: ['regime analysis', 'expression design', 'cross-asset linkage'],
    metrics: ['carry profile', 'expected move to catalyst', 'portfolio beta contribution'],
    firms: ['Bridgewater', 'Brevan Howard', 'Caxton', 'Rokos Capital'],
    firmType: 'hedge_fund',
    tags: ['macro', 'cross-asset', 'regimes'],
  },
  {
    role: 'consulting',
    subcategory: 'strategy',
    label: 'Strategy Consulting',
    product: 'growth, market entry, and corporate strategy advice',
    deliverable: 'structure an ambiguous problem and recommend an economically sound path forward',
    counterpart: 'clients, partners, and case teams',
    workflow: 'clarify the objective, build the issue tree, test hypotheses, and communicate a clear recommendation',
    focus: 'bringing structure fast without losing commercial judgment',
    coreSignal: 'whether your recommendation is practical, quantified, and clearly tied to the client goal',
    drivers: ['market attractiveness', 'competitive position', 'economic impact'],
    risks: ['overcomplicating the problem', 'weak prioritization', 'not sizing the economics'],
    skills: ['problem structuring', 'quantitative reasoning', 'executive communication'],
    metrics: ['market size', 'profit pool impact', 'implementation feasibility'],
    firms: ['McKinsey', 'Bain', 'BCG', 'Oliver Wyman'],
    firmType: 'consulting_firm',
    tags: ['strategy', 'problem-solving', 'structured-thinking'],
  },
  {
    role: 'consulting',
    subcategory: 'general_consulting',
    label: 'General Consulting',
    product: 'broad operational and strategic advisory',
    deliverable: 'bring rigorous analysis to messy client problems and help teams execute change',
    counterpart: 'clients, managers, and analysts',
    workflow: 'frame the problem, gather facts, test hypotheses, and land the recommendation with stakeholders',
    focus: 'combining analysis with change management and stakeholder awareness',
    coreSignal: 'whether the analysis changes a client decision and can actually be implemented',
    drivers: ['client objective clarity', 'stakeholder alignment', 'quality of the fact base'],
    risks: ['analysis without actionability', 'stakeholder resistance', 'poor synthesis'],
    skills: ['structured analysis', 'stakeholder management', 'clear synthesis'],
    metrics: ['cost savings potential', 'execution timeline', 'stakeholder adoption'],
    firms: ['Accenture', 'EY-Parthenon', 'Deloitte', 'Kearney'],
    firmType: 'consulting_firm',
    tags: ['consulting', 'implementation', 'stakeholders'],
  },
  {
    role: 'consulting',
    subcategory: 'case_interview',
    label: 'Case Interview',
    product: 'live business problem solving under time pressure',
    deliverable: 'show a clean, hypothesis-driven approach rather than reciting memorized frameworks',
    counterpart: 'the interviewer and, by extension, the client',
    workflow: 'confirm the objective, structure the case, prioritize analyses, and synthesize crisply',
    focus: 'moving from framework to insight rather than getting stuck listing buckets',
    coreSignal: 'whether your structure is MECE enough to guide the case and flexible enough to adapt',
    drivers: ['clarity of objective', 'case structure', 'quality of synthesis'],
    risks: ['rambling', 'generic frameworks', 'forgetting to answer the client question'],
    skills: ['structuring ambiguity', 'mental math', 'synthesis'],
    metrics: ['math accuracy', 'prioritization quality', 'recommendation clarity'],
    firms: ['McKinsey', 'Bain', 'BCG', 'LEK Consulting'],
    firmType: 'consulting_firm',
    tags: ['case', 'interview', 'mental-math'],
  },
  {
    role: 'general_finance',
    subcategory: null,
    label: 'General Finance',
    product: 'broad finance problem solving across valuation, markets, and accounting',
    deliverable: 'show that you can connect core financial concepts to real decisions',
    counterpart: 'interviewers from mixed finance backgrounds',
    workflow: 'define the problem, identify the key economic driver, and explain the trade-off clearly',
    focus: 'linking technical knowledge to judgment instead of reciting definitions',
    coreSignal: 'whether you can explain why a concept matters in an investing or corporate decision',
    drivers: ['cash flow quality', 'cost of capital', 'capital allocation'],
    risks: ['memorized answers', 'weak commercial judgment', 'missing the linkage between statements'],
    skills: ['accounting fluency', 'valuation basics', 'clear reasoning'],
    metrics: ['return on invested capital', 'free cash flow conversion', 'leverage capacity'],
    firms: ['Goldman Sachs', 'J.P. Morgan', 'BlackRock', 'RBC Capital Markets'],
    firmType: 'general_finance',
    tags: ['finance', 'technical', 'fundamentals'],
  },
  {
    role: 'behavioural',
    subcategory: null,
    label: 'Behavioural',
    product: 'judgment, self-awareness, and teammate quality',
    deliverable: 'convince the interviewer that you can perform under pressure and be trusted on a team',
    counterpart: 'future teammates and managers',
    workflow: 'give a concrete example, explain your decision process, and show the lesson you carried forward',
    focus: 'self-awareness paired with accountability',
    coreSignal: 'whether your examples show maturity, ownership, and coachability instead of polished clichés',
    drivers: ['clarity of example', 'ownership of mistakes', 'quality of reflection'],
    risks: ['vague anecdotes', 'blaming others', 'answers that sound rehearsed but shallow'],
    skills: ['self-reflection', 'communication', 'team judgment'],
    metrics: ['clarity under pressure', 'quality of reflection', 'evidence of growth'],
    firms: ['Goldman Sachs', 'McKinsey', 'Citadel', 'CPP Investments'],
    firmType: 'general_finance',
    tags: ['behavioural', 'fit', 'leadership'],
  },
];

const BLUEPRINTS: QuestionBlueprint[] = [
  {
    key: 'why-track',
    questionType: 'fit',
    difficulty: 'easy',
    tags: ['motivation', 'why-this-role'],
    buildQuestion: (meta, firm) => `Why ${meta.label.toLowerCase()} at ${firm}, and what do you think people underestimate about the job?`,
    buildAnswer: (meta, firm) =>
      `I am drawn to ${meta.label.toLowerCase()} because it combines ${meta.skills[0]} with ${meta.skills[1]} in a setting where feedback is immediate and accountability is clear. What people underestimate is that the job is not just about being smart; it is about having a repeatable process that helps a team ${meta.deliverable}. At ${firm}, I would want to contribute by learning the core workflow quickly, building trust through reliable execution, and showing that I can stay calm when the signal is noisy. The role fits me because I enjoy high standards, fast learning loops, and turning a messy problem into a clear decision.`,
  },
  {
    key: 'day-one-process',
    questionType: 'technical',
    difficulty: 'medium',
    tags: ['process', 'workflow'],
    buildQuestion: (meta) => `If I dropped you into a ${meta.label.toLowerCase()} seat tomorrow morning, how would you structure your first hour?`,
    buildAnswer: (meta) =>
      `My first hour would be about orientation before action. I would start by clarifying the day’s objectives, risk limits, and major catalysts, then review the most important information tied to ${meta.coreSignal}. After that I would look at ${meta.drivers[0]}, ${meta.drivers[1]}, and ${meta.drivers[2]} to frame the opportunity set. Only once I understand the context would I move into the actual ${meta.workflow}, because in this role early discipline matters more than acting fast without a frame.`,
  },
  {
    key: 'key-driver',
    questionType: 'market',
    difficulty: 'medium',
    tags: ['market-view', 'drivers'],
    buildQuestion: (meta) => `What is one driver you would watch most closely in ${meta.label.toLowerCase()} right now, and why?`,
    buildAnswer: (meta) =>
      `One driver I would prioritize is ${meta.drivers[0]} because it directly changes how attractive ${meta.product} looks on a forward basis. I would not view it in isolation, though. I would pair it with ${meta.drivers[1]} and ${meta.drivers[2]} to see whether the story is confirming or starting to fracture. The practical goal is to translate the macro or operating signal into a concrete question: does it improve the expected payoff enough to justify the risk, or is the market already pricing it in?`,
  },
  {
    key: 'pitch-idea',
    questionType: 'case',
    difficulty: 'hard',
    tags: ['idea-generation', 'thesis'],
    buildQuestion: (meta) => `Pitch me a simple idea that would fit a ${meta.label.toLowerCase()} team and walk me through how you would underwrite it.`,
    buildAnswer: (meta) =>
      `I would start with a setup where ${meta.drivers[0]} is changing faster than the market appreciates. Then I would test whether the cleanest expression in ${meta.product} offers enough upside relative to the key risks of ${meta.risks[0]} and ${meta.risks[1]}. My underwriting would be explicit: what is the thesis, what is the catalyst, what would falsify the view, and what size is appropriate if I am wrong on timing but right on direction. A good idea for this seat is not just interesting; it has to survive costs, liquidity, and the discipline required to exit when the thesis breaks.`,
  },
  {
    key: 'risk-framework',
    questionType: 'technical',
    difficulty: 'hard',
    tags: ['risk-management', 'discipline'],
    buildQuestion: (meta) => `How would you think about risk management in ${meta.label.toLowerCase()} before you put capital or credibility at risk?`,
    buildAnswer: (meta) =>
      `I would define risk before I touch the opportunity. That means identifying the specific ways the thesis could fail, especially ${meta.risks[0]}, ${meta.risks[1]}, and ${meta.risks[2]}. From there I would decide whether the risk is fundamental, timing-related, or structural, because each one deserves a different response. The final step is to align sizing and communication with the actual uncertainty: if the downside is hard to hedge or the feedback loop is slow, the bar for conviction and for exposure has to be much higher.`,
  },
  {
    key: 'core-skill',
    questionType: 'technical',
    difficulty: 'medium',
    tags: ['skills', 'technical-edge'],
    buildQuestion: (meta) => `What technical skill matters most in ${meta.label.toLowerCase()}, and how would you prove you have it?`,
    buildAnswer: (meta) =>
      `The skill I would emphasize first is ${meta.skills[0]}, because without it the rest of the process becomes reactive rather than repeatable. I would pair that with ${meta.skills[1]} and ${meta.skills[2]} so the output is not just technically correct but actually useful in a live setting. To prove it, I would walk through a specific example where I framed the problem, chose a sensible method, and then showed how the answer changed a decision. In this kind of role, evidence of judgment matters at least as much as evidence of raw horsepower.`,
  },
  {
    key: 'product-explain',
    questionType: 'product',
    difficulty: 'medium',
    tags: ['product-knowledge', 'communication'],
    buildQuestion: (meta) => `Explain ${meta.product} to a smart senior person in plain English. What are the two or three things that really matter?`,
    buildAnswer: (meta) =>
      `I would explain ${meta.product} as a tool for expressing a view or helping a client solve a real problem, not as jargon for its own sake. The first thing that matters is the source of return or value creation: how does it help the team ${meta.deliverable}. The second is what drives the economics, especially ${meta.drivers[0]} and ${meta.drivers[1]}. The third is risk, because even a compelling product can disappoint if you ignore ${meta.risks[0]} or the practical cost of executing it.`,
  },
  {
    key: 'stress-scenario',
    questionType: 'case',
    difficulty: 'hard',
    tags: ['scenario-analysis', 'stress-test'],
    buildQuestion: (meta) => `Your view is directionally right, but the market moves against you first. How would you stress-test a ${meta.label.toLowerCase()} idea in that situation?`,
    buildAnswer: (meta) =>
      `I would separate thesis risk from path risk immediately. First I would ask whether the move against me is new information that invalidates the original idea or simply noise around timing. Then I would rebuild the scenario using the most important risk channels, especially ${meta.risks[0]} and ${meta.risks[1]}, and see how the expected payoff changes under realistic stress assumptions. If the thesis survives and the payoff still makes sense, I can stay disciplined; if not, the right answer is to cut or resize rather than defend sunk cost.`,
  },
  {
    key: 'metrics',
    questionType: 'technical',
    difficulty: 'medium',
    tags: ['monitoring', 'kpis'],
    buildQuestion: (meta) => `What metrics would you monitor every week to know whether you are getting better in ${meta.label.toLowerCase()}?`,
    buildAnswer: (meta) =>
      `I would track a mix of outcome and process metrics. On the outcome side I would watch ${meta.metrics[0]} and ${meta.metrics[1]} because they tell me whether the decisions are translating into value. On the process side I would monitor ${meta.metrics[2]} or its closest practical equivalent, because a strong outcome can still hide bad process during a lucky stretch. The point is to create a feedback loop that tells me whether the edge is real, repeatable, and consistent with the role’s actual objective.`,
  },
  {
    key: 'mistake',
    questionType: 'fit',
    difficulty: 'medium',
    tags: ['mistakes', 'accountability'],
    buildQuestion: (meta) => `Tell me about a mistake that would be especially dangerous in ${meta.label.toLowerCase()} and how you would prevent it.`,
    buildAnswer: (meta) =>
      `A dangerous mistake in this seat is acting with false confidence when the inputs are incomplete. In practice that often shows up as ${meta.risks[0]} or ${meta.risks[1]}. The prevention is procedural: write down the thesis, define what would disprove it, and force a second check before escalating size or recommending action. I would rather look slightly conservative for five minutes than spend weeks cleaning up an error that came from skipping process.`,
  },
  {
    key: 'communication',
    questionType: 'fit',
    difficulty: 'medium',
    tags: ['communication', 'stakeholders'],
    buildQuestion: (meta) => `How would you communicate a difficult message to ${meta.counterpart} in a ${meta.label.toLowerCase()} setting?`,
    buildAnswer: (meta) =>
      `I would keep the communication direct, specific, and decision-oriented. First I would frame the message around what changed, why it matters, and what action I recommend now. Then I would translate the underlying analysis into the language the audience actually needs, whether that is risk, timeline, or economic impact. In a strong team, credibility comes from being calm and clear when the news is uncomfortable, not from sounding polished while avoiding the real issue.`,
  },
  {
    key: 'why-firm',
    questionType: 'fit',
    difficulty: 'easy',
    tags: ['firm-specific', 'motivation'],
    buildQuestion: (meta, firm) => `Why would you choose ${firm} over another platform for ${meta.label.toLowerCase()}?`,
    buildAnswer: (meta, firm) =>
      `I would choose ${firm} if I believed it gave me the strongest environment to learn the craft properly and contribute at a high standard. In ${meta.label.toLowerCase()}, that means a place where people care deeply about ${meta.focus}, where the team is honest about mistakes, and where the process behind ${meta.deliverable} is respected rather than improvised. I would make the decision based on whether the platform is known for strong feedback, real responsibility early, and a culture where good judgment is rewarded more than empty confidence.`,
  },
  {
    key: 'ethics',
    questionType: 'fit',
    difficulty: 'medium',
    tags: ['ethics', 'judgment'],
    buildQuestion: (meta) => `What does good judgment and integrity look like in ${meta.label.toLowerCase()} when the pressure is on?`,
    buildAnswer: (meta) =>
      `Good judgment under pressure means staying faithful to the process even when speed, ego, or short-term optics tempt you to cut corners. In this role, that means being explicit about what you know, what you do not know, and where the real risk sits, especially around ${meta.risks[2]}. Integrity shows up in the small habits: documenting assumptions, escalating issues early, and never hiding a mistake because you hope the market or the client will bail you out later. Teams trust people who protect the franchise when it is hardest, not when it is easy.`,
  },
  {
    key: 'learning-plan',
    questionType: 'market',
    difficulty: 'medium',
    tags: ['learning', 'research-habits'],
    buildQuestion: (meta) => `How would you build a learning plan for your first 90 days in ${meta.label.toLowerCase()}?`,
    buildAnswer: (meta) =>
      `My first 90 days would have three parts. First I would learn the operating language of the seat: the products, metrics, and recurring decisions that matter most, especially around ${meta.metrics[0]} and ${meta.metrics[1]}. Second I would build a compact playbook around ${meta.workflow} so I understand how good decisions are actually made on this team. Third I would keep a weekly log of what changed my view, what surprised me, and where I made avoidable mistakes, because the fastest improvement usually comes from tightening the loop between observation and correction.`,
  },
];

function createSeedQuestion(meta: TrackMeta, blueprint: QuestionBlueprint, index: number): InterviewSeedQuestion {
  const firm = meta.firms[index % meta.firms.length];
  const seedKey = slugifyValue([
    meta.role,
    meta.subcategory ?? 'general',
    blueprint.key,
    firm,
  ].join('-'));

  return {
    seedKey,
    question: blueprint.buildQuestion(meta, firm),
    answer: blueprint.buildAnswer(meta, firm),
    notes: null,
    role: meta.role,
    subcategory: meta.subcategory,
    questionType: blueprint.questionType,
    difficulty: blueprint.difficulty,
    company: firm,
    firmType: meta.firmType,
    topicTags: Array.from(new Set([...meta.tags, ...blueprint.tags])),
    sourceType: 'sgc_editorial_seed',
    sourceTitle: SOURCE_TITLE,
    sourceUrl: null,
    attachmentUrl: null,
    submitterName: 'SGC Editorial',
    submittedBy: null,
    approved: true,
  };
}

export function buildInterviewSeedQuestions() {
  return TRACKS.flatMap((meta) => BLUEPRINTS.map((blueprint, index) => createSeedQuestion(meta, blueprint, index)));
}
