import { NextResponse } from 'next/server';

export const revalidate = 86400; // refresh once per day

const TERMS: { term: string; definition: string; category: string }[] = [
  { term: 'Alpha', definition: 'Excess return generated relative to a benchmark index after adjusting for risk. An alpha of 1% means the portfolio outperformed by 1% beyond what its beta exposure predicts.', category: 'Portfolio Theory' },
  { term: 'Beta', definition: 'Measure of a security\'s systematic volatility relative to the market. A beta of 1.2 means the asset historically moves 20% more than the index in either direction.', category: 'Portfolio Theory' },
  { term: 'Sharpe Ratio', definition: 'Risk-adjusted return metric: (portfolio return − risk-free rate) ÷ standard deviation of returns. A ratio above 1.0 is generally considered acceptable; above 2.0 is excellent.', category: 'Portfolio Theory' },
  { term: 'Duration', definition: 'Sensitivity of a bond\'s price to a 1% change in interest rates, measured in years. A bond with duration of 5 will fall roughly 5% in price if rates rise 1%.', category: 'Fixed Income' },
  { term: 'Convexity', definition: 'The rate of change of duration as interest rates move. Positive convexity means price gains from rate drops exceed price losses from equivalent rate rises — a desirable property for bondholders.', category: 'Fixed Income' },
  { term: 'Yield Curve', definition: 'A line plotting interest rates on bonds of equal credit quality but differing maturities. Its shape (normal, flat, or inverted) is one of the most watched macro indicators in finance.', category: 'Fixed Income' },
  { term: 'Basis Points', definition: 'A unit equal to 1/100th of 1% (0.01%). Used to precisely communicate changes in interest rates, credit spreads, and yields. 50 basis points = 0.50%.', category: 'Fixed Income' },
  { term: 'Drawdown', definition: 'Peak-to-trough decline in portfolio value over a specific period. Maximum drawdown captures the worst such decline historically and is a key measure of downside risk.', category: 'Risk Management' },
  { term: 'VIX', definition: 'The CBOE Volatility Index — often called the "fear gauge." It measures the market\'s 30-day implied volatility expectation derived from S&P 500 options. Readings above 30 signal elevated fear.', category: 'Derivatives' },
  { term: 'EBITDA', definition: 'Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash generation stripped of capital structure and accounting choices, widely used in LBO and M&A valuation.', category: 'Valuation' },
  { term: 'Discounted Cash Flow', definition: 'A valuation method estimating the present value of expected future cash flows using a discount rate (typically WACC). The intrinsic value of an asset equals the sum of its discounted future cash flows.', category: 'Valuation' },
  { term: 'P/E Ratio', definition: 'Price-to-Earnings — the most common equity valuation multiple. Divides current share price by earnings per share. A high P/E implies the market expects strong future growth.', category: 'Valuation' },
  { term: 'EV/EBITDA', definition: 'Enterprise Value divided by EBITDA. A capital-structure-neutral valuation multiple allowing comparison across companies with different debt levels. Typically ranges from 6–12x for mature businesses.', category: 'Valuation' },
  { term: 'WACC', definition: 'Weighted Average Cost of Capital — the blended required return on a firm\'s capital (equity + debt), weighted by their proportions. Used as the discount rate in DCF models.', category: 'Valuation' },
  { term: 'IRR', definition: 'Internal Rate of Return — the discount rate that makes the Net Present Value of all cash flows equal to zero. A project is attractive when its IRR exceeds the cost of capital.', category: 'Valuation' },
  { term: 'Enterprise Value', definition: 'Market capitalisation plus total debt minus cash. Represents the theoretical acquisition cost of a business and is capital-structure-neutral, unlike market cap alone.', category: 'Valuation' },
  { term: 'Free Cash Flow', definition: 'Operating cash flow minus capital expenditures. Represents the cash a business generates after maintaining and expanding its asset base — the lifeblood of DCF models.', category: 'Valuation' },
  { term: 'Net Present Value', definition: 'Sum of all discounted future cash flows minus the initial investment. A positive NPV means the investment creates value at the given discount rate.', category: 'Valuation' },
  { term: 'Leverage', definition: 'The use of borrowed capital to amplify potential returns (and losses). Financial leverage is measured by debt-to-equity or debt-to-EBITDA ratios.', category: 'Capital Structure' },
  { term: 'Liquidity', definition: 'The ease with which an asset can be bought or sold without materially affecting its price. Highly liquid assets (e.g., large-cap equities, T-bills) can be transacted quickly at fair value.', category: 'Markets' },
  { term: 'Volatility', definition: 'Statistical measure of the dispersion of returns, typically expressed as annualised standard deviation. Higher volatility implies greater uncertainty and is both a risk measure and an options pricing input.', category: 'Risk Management' },
  { term: 'Correlation', definition: 'Ranges from −1 to +1 and measures how two assets move relative to each other. A correlation of 0 indicates independence; −1 means perfect inverse movement. Diversification exploits low or negative correlation.', category: 'Portfolio Theory' },
  { term: 'Z-Score', definition: 'The number of standard deviations a data point sits from the distribution mean. In quant finance, used to identify statistically significant price moves and to standardise factors.', category: 'Quantitative' },
  { term: 'Momentum', definition: 'The tendency for assets with strong recent performance to continue outperforming over the near term. One of the most robust and persistent return factors documented in academic literature.', category: 'Factor Investing' },
  { term: 'Mean Reversion', definition: 'The tendency for asset prices or spreads to revert toward their long-run historical average over time. Underpins pairs trading, statistical arbitrage, and many fixed income strategies.', category: 'Quantitative' },
  { term: 'Arbitrage', definition: 'Simultaneous purchase and sale of an asset in different markets to profit from a price discrepancy. Pure arbitrage is risk-free; in practice most "arbitrage" carries execution or basis risk.', category: 'Trading' },
  { term: 'Delta', definition: 'The rate of change in an option\'s price for a $1 move in the underlying asset. A delta of 0.60 means the option gains $0.60 for each $1 rise in the stock, and also approximates the probability of expiring in-the-money.', category: 'Derivatives' },
  { term: 'Gamma', definition: 'The rate of change of delta per $1 move in the underlying. High gamma near expiry means delta can shift rapidly, creating large hedging costs for option sellers.', category: 'Derivatives' },
  { term: 'Theta', definition: 'The daily rate of decline in an option\'s value due to the passage of time, all else equal. Option buyers face negative theta (time decay working against them); sellers collect it.', category: 'Derivatives' },
  { term: 'Vega', definition: 'Sensitivity of an option\'s price to a 1-percentage-point change in implied volatility. Long options have positive vega — they gain value if vol rises. Short options lose value.', category: 'Derivatives' },
  { term: 'Implied Volatility', definition: 'The market\'s forward-looking expectation of how much an asset will move, extracted from option prices using a model like Black-Scholes. It represents consensus uncertainty and is the key input priced in options premiums.', category: 'Derivatives' },
  { term: 'Carry Trade', definition: 'Borrowing in a low-interest-rate currency and investing the proceeds in a higher-yielding currency or asset. Profitable in calm markets, but subject to sudden reversal ("carry unwind") during risk-off episodes.', category: 'Macro' },
  { term: 'Short Selling', definition: 'Borrowing shares and selling them, hoping to repurchase at a lower price. Profits from price declines. Involves unlimited theoretical downside risk and borrowing costs that reduce the return.', category: 'Trading' },
  { term: 'Hedge', definition: 'A position taken to offset the risk of an existing exposure. Perfect hedging eliminates risk but also eliminates upside. Most real-world hedges are partial, reducing — not eliminating — risk.', category: 'Risk Management' },
  { term: 'Value at Risk (VaR)', definition: 'The maximum expected portfolio loss over a given time horizon at a specified confidence level. A 1-day 95% VaR of $1M means there is a 5% chance of losing more than $1M in a single day.', category: 'Risk Management' },
  { term: 'Credit Spread', definition: 'The yield difference between a corporate bond and a risk-free government bond of the same maturity. Compensates investors for default risk; widens during recessions and credit stress events.', category: 'Fixed Income' },
  { term: 'Yield to Maturity', definition: 'The total annualised return an investor earns if they hold a bond to maturity and all coupon payments are reinvested at the same rate. The single most important bond pricing metric.', category: 'Fixed Income' },
  { term: 'Quantitative Easing', definition: 'Central bank asset purchases (government bonds, MBS) that inject reserves into the banking system, lower long-term yields, and stimulate lending. Deployed at the zero lower bound when rate cuts are exhausted.', category: 'Macro' },
  { term: 'Federal Funds Rate', definition: 'The target interest rate set by the FOMC at which U.S. banks lend excess reserves to each other overnight. The most important policy rate in the world — it anchors the entire dollar yield curve.', category: 'Macro' },
  { term: 'Inverted Yield Curve', definition: 'Occurs when short-term yields exceed long-term yields. Historically one of the most reliable recession predictors — the 2Y/10Y inversion preceded every U.S. recession since the 1970s.', category: 'Macro' },
  { term: 'Pairs Trading', definition: 'A market-neutral strategy that goes long one security and short a highly correlated one when their spread diverges. The bet is that the spread will revert; profit is independent of market direction.', category: 'Quantitative' },
  { term: 'Information Ratio', definition: 'Active return divided by tracking error (active risk). Measures the consistency of an active manager\'s outperformance. A ratio above 0.5 is considered good; above 1.0 is exceptional.', category: 'Portfolio Theory' },
  { term: 'Sortino Ratio', definition: 'A variant of the Sharpe Ratio that only penalises downside deviation rather than total volatility. Preferred when return distributions are asymmetric (e.g. strategies with positive skew).', category: 'Portfolio Theory' },
  { term: 'Maximum Drawdown', definition: 'The largest peak-to-trough decline in portfolio value over a measurement period. A critical risk metric for investors who cannot afford large capital losses or have redemption constraints.', category: 'Risk Management' },
  { term: 'Efficient Frontier', definition: 'The set of optimal portfolios offering the highest expected return for a given level of risk, or the lowest risk for a given return — derived from Markowitz\'s Modern Portfolio Theory.', category: 'Portfolio Theory' },
  { term: 'CAPM', definition: 'Capital Asset Pricing Model: expected return = risk-free rate + beta × (market return − risk-free rate). The bedrock model linking systematic risk (beta) to required return and the foundation of much of modern finance.', category: 'Portfolio Theory' },
  { term: 'Factor Investing', definition: 'A strategy explicitly targeting specific return drivers — value, momentum, size, quality, low volatility. Systematic exposure to well-documented factors can harvest persistent risk premia.', category: 'Factor Investing' },
  { term: 'Mark to Market', definition: 'Valuing assets at their current market price rather than historical cost. Forces daily P&L recognition. Used in futures, derivatives, and hedge fund accounting; can amplify losses in illiquid markets.', category: 'Markets' },
  { term: 'Spread', definition: 'The difference between two prices or rates. Can refer to the bid-ask spread (market microstructure), credit spread (fixed income), or the spread between two securities in a relative-value trade.', category: 'Markets' },
  { term: 'Covariance', definition: 'A statistical measure of how two assets move together. Positive covariance = same direction; negative = opposite. The building block of the portfolio variance calculation and correlation.', category: 'Quantitative' },
  { term: 'Skewness', definition: 'Measures asymmetry in the distribution of returns. Negative skew (left tail) means occasional large losses. Strategies that collect premium (options selling) typically exhibit negative skew.', category: 'Risk Management' },
  { term: 'Kurtosis', definition: 'Measures the "fat-tailedness" of a return distribution. High kurtosis (leptokurtosis) means extreme outcomes occur more often than a normal distribution predicts — a critical consideration for tail risk.', category: 'Risk Management' },
  { term: 'Basis Risk', definition: 'The residual risk from an imperfect hedge — when the hedging instrument doesn\'t perfectly offset the position being hedged. Common in cross-hedging with futures or when correlations shift.', category: 'Risk Management' },
  { term: 'Repo Rate', definition: 'Short for repurchase agreement rate. A borrower sells securities and agrees to repurchase them at a higher price. Repos are a primary funding mechanism for broker-dealers and the fixed income market.', category: 'Fixed Income' },
  { term: 'R-Squared', definition: 'Proportion of a portfolio\'s return variance explained by benchmark movements. A high R-squared (near 1.0) means returns are largely explained by the index — signalling a "closet index fund."', category: 'Portfolio Theory' },
  { term: 'Tracking Error', definition: 'The standard deviation of the difference between portfolio returns and benchmark returns. Measures how closely a portfolio follows its benchmark. High tracking error = high active risk.', category: 'Portfolio Theory' },
  { term: 'High-Frequency Trading', definition: 'Algorithmic trading executing thousands of orders per second using co-located servers. Profits from tiny price discrepancies and market microstructure. Accounts for a significant share of U.S. equity volume.', category: 'Trading' },
  { term: 'Dark Pool', definition: 'A private trading venue where large institutional orders are executed away from public exchanges to minimise market impact. Trades are reported post-execution, not shown in real-time order books.', category: 'Markets' },
  { term: 'Calmar Ratio', definition: 'Annualised return divided by maximum drawdown. Favoured by CTA and systematic traders to evaluate return relative to worst-case loss. Higher is better.', category: 'Portfolio Theory' },
  { term: 'Contango', definition: 'When futures prices are higher than the expected spot price — the normal condition for commodities with storage costs. Investors rolling futures in contango pay a "roll cost" as they sell cheaper near-month contracts and buy more expensive far-month ones.', category: 'Derivatives' },
  { term: 'Backwardation', definition: 'When futures prices are below the expected spot price, often when spot demand is high and supply is tight. Rolling long futures positions in backwardation generates positive roll yield.', category: 'Derivatives' },
  { term: 'Sovereign Spread', definition: 'The yield premium demanded by investors to hold a government\'s debt over a risk-free benchmark (typically U.S. Treasuries). Reflects perceived fiscal sustainability, political risk, and currency risk.', category: 'Macro' },
];

export async function GET() {
  // Deterministic rotation: one new term per calendar day
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86_400_000
  );
  const term = TERMS[dayOfYear % TERMS.length];
  return NextResponse.json(term);
}
